[package]
name = "modern-cornell-notebooks"
version = "0.2.0"
entrypoint = "template/cornell.typ"
license = "MIT"
description = "A Typst template for creating notebooks with cornell style."
repository = "https://github.com/aFei-CQUT/cornell-notebooks"
authors = ["aFei-CQUT <https://github.com/aFei-CQUT>"]
categories = ["book"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "cornell.typ"
thumbnail = "thumbnail.png"

[export]
files = [
    "layouts/*.typ",
    "pages/*.typ",
    "lib/lib.typ",
    "utils/*.typ",
    "template/cornell.typ",
    "template/refs.bib",
    "images/typst.png",
]
